name: Parse XHTTP

on:
  push:
    paths:
      - 'python/xhttp.py'
      - '.github/workflows/xhttp.yml'

  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run xhttp script
      run: python python/xhttp.py
      
    - name: Check for Changes
      id: changes
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Changes
      if: steps.changes.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push
